version: "3.7"
services:
    api:
        build: .
        image: grzegorzjudas/express-starter
        env_file:
            - env-local.env
            - env-docker.env
        ports:
            - "8080:80"
        depends_on:
            - db
            - cache
            - jaeger
    db:
        image: postgres:12-alpine
        ports:
            - "5432:5432"
        env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: express-starter
    cache:
        image: redis:6-alpine
        ports:
            - "6379:6379"
        command: ["redis-server", "--requirepass", "redis"]
    jaeger:
        image: jaegertracing/all-in-one
        ports:
            - "16686:16686"
